name: robofishbot
services:
  - name: bot
    environment_slug: docker
    git:
      repo_clone_url: https://github.com/RyanO-K/RoboBanana.git
      branch: main
    build_command: docker build -t robofishbot .
    run_command: docker-compose up -d bot
    envs:
      - key: SOME_SECRET
        scope: RUN_TIME
        value: ${SOME_SECRET_FROM_REPOSITORY}
  - name: server
    environment_slug: docker
    git:
      repo_clone_url: https://github.com/RyanO-K/RoboBanana.git
      branch: main
    build_command: docker build -t robofishbot-server -f ./server/Dockerfile .
    run_command: docker-compose up -d server
    http_port: 3000
  - name: cache
    environment_slug: docker
    image: redis:alpine
    run_command: redis-server
    http_port: 6379
    healthcheck:
      - command: ["redis-cli", "ping"]
        interval: 10s
        timeout: 1s
        retries: 3

