name: sample
services:
- name: sample
  envs:
  - key: SOME_SECRET
    value: ${SOME_SECRET_FROM_REPOSITORY} # TODO - BRING SECRETS.YAML OVER
    type: SECRET
  github:
    branch: main
    repo: RyanO-K/RoboBanana
    
