name: robofishbot
services:
  - name: bot
    github:
      repo: RyanO-K/RoboBanana
      branch: main
    dockerfile_path: ./Dockerfile
    http_port: 3000
    routes:
      - path: /bot
    envs:
      - key: SOME_SECRET
        scope: RUN_TIME
        value: ${SOME_SECRET_FROM_REPOSITORY}

  - name: server
    github:
      repo: RyanO-K/RoboBanana
      branch: main
    dockerfile_path: ./server/Dockerfile
    http_port: 3000
    routes:
      - path: /server

  - name: cache
    image:
      registry_type: DOCKER_HUB
      repository: redis
      tag: alpine
    http_port: 6379
    healthcheck:
      - command: ["redis-cli", "ping"]
        interval: 10s
        timeout: 1s
        retries: 3
