name: robofishbot
services:
  - name: bot
    github:
      repo: RyanO-K/RoboBanana
      branch: config_yaml
    dockerfile_path: ./Dockerfile
    http_port: 3000
    routes:
      - path: /bot
    envs:
      - key: DISCORD_TOKEN
        scope: RUN_TIME
        value: ${{ secrets.DISCORD_TOKEN }}
      - key: DATABASE_PASSWORD
        scope: RUN_TIME
        value: ${{ secrets.DB_PASSWORD }} 
      - key: SERVER_TOKEN
        scope: RUN_TIME
        value: ${{ secrets.SERVER_TOKEN }} 

  - name: server
    github:
      repo: RyanO-K/RoboBanana
      branch: config_yaml
    dockerfile_path: ./server/Dockerfile
    http_port: 3000
    routes:
      - path: /server
    env:
      - key: DISCORD_TOKEN
        scope: RUN_TIME
        value: ${{ secrets.DISCORD_TOKEN }}
      - key: DATABASE_PASSWORD
        scope: RUN_TIME
        value: ${{ secrets.DB_PASSWORD }} 
      - key: SERVER_TOKEN
        scope: RUN_TIME
        value: ${{ secrets.SERVER_TOKEN }} 

  - name: cache
    image:
      registry_type: DOCKER_HUB
      repository: redis
      tag: alpine
    http_port: 6379
    healthcheck:
      - command: ["redis-cli", "ping"]
        interval: 10s
        timeout: 1s
        retries: 3
    env:
      - key: DISCORD_TOKEN
        scope: RUN_TIME
        value: ${{ secrets.DISCORD_TOKEN }}
      - key: DATABASE_PASSWORD
        scope: RUN_TIME
        value: ${{ secrets.DB_PASSWORD }} 
      - key: SERVER_TOKEN
        scope: RUN_TIME
        value: ${{ secrets.SERVER_TOKEN }} 
