name: Update App

on:
 push:
   branches: [config_yaml]

jobs:
 deploy-app:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Deploy the app
       uses: digitalocean/app_action/deploy@v2
       with:
         token: ${{ secrets.TOKEN }} 
       env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }} 
        DATABASE_PASSWORD: ${{ secrets.DB_PASSWORD }} 
        SERVER_TOKEN: ${{ secrets.SERVER_TOKEN }} 
