name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 159.89.252.139
          username: ${{ secrets.USERNAME }}
          key: -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAACmFlczI1Ni1jdHIAAAAGYmNyeXB0AAAAGAAAABBDzIJ/IA
PZlIVV5YE6mBsxAAAAEAAAAAEAAAGXAAAAB3NzaC1yc2EAAAADAQABAAABgQDgj97WY7Za
HT9Mc2rBbnWy96ituSRkJ6APHVIvI9GAdpSRh1dfUa803RUlZbNSZFk33NTkV+0LTut42i
9rkHl8JVo8tUC1jvzwhTpB6+/I3SfpH+GLs0yOm3wIO6uQKbQUEL3mXysViiIkKexx0ndr
UnJHAwyvmWAAZkEtr7itM5JtFFWwK/ZvJN9P8eTkQRZTQErDkSA1SGf4U3pEZjplAOMh/z
XM3B/5FME9NdcT6vCBmCVMXLiJZNRaoBub2vvTgaKXHizmeDNP0A03rkBIs+YEII/ekhfY
6YYPsoUVAeA9V91Kvqvt5aSh9gHLd5bxpY0jnm4sNQbaqj5gYSYw/wWLVZHcaDN3Hbq53d
2cFgWpV+KIaek6ahuCamDwajbVlHDlkO3BT3M8z6g4hRM6fnM3crBZvjJI05lbyEo/ItnP
hYl9wpzaDBAxoysKrTUREbom2KRzmrXqro6J+ubOYPCPsFGRcYmrAzmCEN8oHGYR0ayGt0
1I1DYwpa+kt/sAAAWgaO5n3EDnNO2pHprUf24SJ4cBEXWBv7OPmm+i2jz9PdbwqOicpLcc
tKclz3dhUWDarqdzMUNtsnWcup+TlbYdBatMgLnXxMqR4f6534kkOgQ20OAP0COsQWRoZe
mp6G47UOVBz2hS0rDhB1B3Rw13PFwl83csxVMpSuiX8ODXtYYvLderl3fvuG7fKXgSIKX7
T1epLEjl8+OwFLpjZp5MNg1b19vlfbvpe23B7KLUVARSME0k75eB4Togq/6omwnxfcQP9E
gYoq53LwQwl4vfAKLZOsAxgI/COmfrVA1zlmjFPJzoQZ+RGd0xL+4voRU3uERZGHB1P/Wb
i/A22p/AcSU84cBfwAGKDOTV+BzW0to886OiUd9ODpkpmwbbwuAQjPs9idvmUawVZbmmYP
3vCG/381dka2t0AtDwQ35oVSRV+miUDOvJ9VeZk0FQWvreJQbsFkNGe9JN62JuR4c/KJry
hPrqnhXuXzTE1bgH8rUc3Ci/tTTfXeix8xLBueZCQQ2YgHoPVxqCJxmR1WObPqhm6y7Ut6
Ua5rZwknWrQtSTIWwQCWYnosn/2GXfo1FYOQCxNAYSs4rhTVQlJymJPjMeXVhRzEIwmeHw
itIy3IqJm4Djf0PQ9O0msrK3noBy8bEvinZEJfTUtu1efXAHy71RQ+MUkPVgCZips8YvyH
D6GihrNGtaeaaWGchhp4rrMO0QaTjzGtWlofA2JuLWzapEx0qEIcyNSKlkqUD4+HyBP3Uq
sR42XnoIpHe15TlRvDuF4vDVjKHVCcTmBpPpubMpCNn+rpyuxzWoxmVnyBQLpkypQr+efV
9CiwMGJ+tK52KMuQ2J8mm4H/u65CzQbXvhTnhBea7rDp3tCBhf0tm2nTWQ/f7eaFhwS7dQ
z89yK67+txXcdBCJp0Er+SmZNocxESvVhaeHQrTRMyLlmi7zMqjltAAN2TZtnR+vQSNRSI
SHnKALeRxWTbNINKU28y3Ipo7EBYcJ7LUG+TFYzjFOItMS8+vZ6I5STzPfiiiNRsx2DjRo
WM0X6NcXgTVfZ1CIJ3Wd97Fhn5F2/d61OYMaDhuU39FH8vPw51jvq1nKlAJMGyzw7Z3Xc6
UJ4jKtBUwSdGhZIX/hVZYqNfNLfN5Cm876A54la2RcvTE/W0+HQiBCwQmeNqUPjraysyxN
8MxgsvVh8eey4eRhhFlainsPRfT0gcM7w7z2IhSt9lISzSTp0b19h0C75gEUxPhhowOALP
p4E0LR93KxH9ftf5kV1cx0Z5vnswuDMpexMEm/F4ScFuFj50DTnzyaRxyZE/qeUnvB8S3d
vF+aVffGgOvdKwyK98Do1s/+BFtYOrvIZNw+LbnYCDzfrnUKJA/UATgTaua/QXwADcGLnP
tbzQBWy0Nae/5n6EYMAgi+PZG5UrSjp3BPilCgEWd3KIS+neEe7TlHU2vAsY9f2aue4gyH
hh2DwYHSOd9gLGfAOclQOj3QE0qyjrP6KYkz5TUwWjaN2sUyMIyOUtcE/iMX+NE+Ji4IRT
IT+5uMAi+x0bqHTmaeEUUYL2TAASxgxK+YM/1yih2MnNCtOuWTTAnyElC1ssytsPC30Ugg
1TOTkeT8VinBuaavtqT3dqFwxYQz9co7K/bc7yF3Dg4qc3biR8d29Co/qfl603gGEkG/a5
hxIWLGzO38qvOjYjfOIP/2jOhyhjiUYhPUatDzfAIIYXJFGY8WSCOHSqleaeImVSEngJGD
d4Ax4oG3PUw3p63fmGiaECwj2Le0xyNgoujeUaOynw9qtpW4GNcrefFYcqgJIbKJcqJ2+G
Ck8W9qrTTibHp1H48xgw3b0cEmplnNXWIIuUc7BvoVZKr7pu2o4ztfnhOFNQkQwOk0bKJ+
tFbxo8NAmEK/xsPO0OEo65FmC/edYpq0km8QuoVpYPoa72tr
-----END OPENSSH PRIVATE KEY-----
          port: ${{ secrets.PORT }}
          
          script: |
            git clone https://github.com/RyanO-K/RoboBanana
            docker compose up

