name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: ${{   secrets.DOCKERHUB_USERNAME }}
          password: $${{  secrets.DOCKERHUB_PASSWORD }}
          repository: RyanO-K/RoboBanana
          tag_withref: true
          tag with sha: true
          
          script: |
            git clone https://github.com/RyanO-K/RoboBanana
            docker compose up
