name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 159.89.252.139
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          
          script: |
            git clone https://github.com/RyanO-K/RoboBanana
            docker compose up

