name: Build & Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker images
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          keys: ${{ secrets.DEPLOY_KEY }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          password: ${{  secrets.PASSKEY }}
          repository: RyanO-K/RoboBanana
          tag_withref: true
          tag with sha: true
          
          script: |
            git clone https://github.com/RyanO-K/RoboBanana
            docker compose up
